### ISSUE TITLE
Geometrycollection

### ISSUE THREAD

**Issue by nanaberry** [alejandrofcarrera/WKTParser-ObjC#2]
Hi, i am using your WKTParser Library in one of my project. Everything was working great. However, i having issue with 'Geometrycollection' and only then i realised it is not included in the library. Is there any workaround to it?

**Comment by alejandrofcarrera** [comment]
hi @nanaberry . Sorry for hearing this because i didn't notice about this issue until now. I don't know if there is any problem with my notifications...

Well, GeometryCollection is included on this library but i can say that i am not using it from some time ago (i didn't test it on the latest Xcode or iOS SDK), so can you put here the WKT that you are trying to parse ? or something that can be help for me to resolve this issue ?

**Comment by alejandrofcarrera** [comment]
Closed issue due to inactivity.
